# Generated by Django 4.2.1 on 2023-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionPerroAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('raza', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('adoptado', models.BooleanField(default=False)),
            ],
        ),
    ]
