# Generated by Django 4.2.1 on 2023-06-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacionperroadopcion',
            name='mails_contactados',
            field=models.JSONField(default=dict, verbose_name='mails_contactados'),
        ),
        migrations.AddField(
            model_name='publicacionperroadopcion',
            name='rango_edad',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Joven', 'Joven'), ('Adulto', 'Adulto')], default='Cachorro', max_length=30),
        ),
        migrations.AddField(
            model_name='publicacionperroadopcion',
            name='tamaño',
            field=models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Chico', max_length=30),
        ),
        migrations.AlterField(
            model_name='publicacionperroadopcion',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
