# Generated by Django 4.2.1 on 2023-06-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='fecha',
            new_name='Fecha',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='franja_horaria',
            new_name='Franja_Horaria',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='pendiente',
            new_name='Pendiente',
        ),
    ]
