# Generated by Django 4.2.1 on 2023-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_rename_descripcion_turno_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='Franja_Horaria',
            field=models.TextField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1),
        ),
    ]
