# Generated by Django 4.2.1 on 2023-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='publicaciones_contactadas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
