# Generated by Django 4.2.1 on 2023-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_publicaciones_contactadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='publicaciones_contactadas',
            field=models.JSONField(default=dict, verbose_name='publicaciones_contactadas'),
        ),
    ]
