# Generated by Django 4.2.2 on 2023-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionPerroPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('encontrado', models.BooleanField(default=False)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('imagen', models.ImageField(blank=True, upload_to='perdidos')),
                ('tamaño', models.CharField(max_length=100)),
                ('rango_edad', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Joven', 'Joven'), ('Adulto', 'Adulto')], max_length=30)),
                ('mails_contactados', models.JSONField(default=dict, verbose_name='mails_contactados')),
            ],
        ),
    ]
