# Generated by Django 4.2.1 on 2023-06-23 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='peso',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='perro',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 23, 17, 37, 638658)),
        ),
        migrations.AddField(
            model_name='perro',
            name='tamaño',
            field=models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Chico', max_length=8),
        ),
        migrations.AlterField(
            model_name='libretavacunas',
            name='tipo',
            field=models.CharField(choices=[('A', 'Antirrabica'), ('M', 'Moquillo')], max_length=1),
        ),
    ]
