# Generated by Django 4.2.1 on 2023-06-23 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_historiaclinica_diagnostico_historiaclinica_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 2, 8, 54, 604551)),
        ),
    ]
