# Generated by Django 4.2.1 on 2023-06-23 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_alter_perro_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 3, 5, 12, 696661)),
        ),
    ]
