# Generated by Django 4.2.1 on 2023-06-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colectas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecta',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
