# Generated by Django 4.2.1 on 2023-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colectas', '0002_colecta_concluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecta',
            name='monto_recaudado',
            field=models.FloatField(default=0),
        ),
    ]
