# Generated by Django 4.2.1 on 2023-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encontrados', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionperroencontrado',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='encontrados'),
        ),
    ]
